### ISSUE TITLE
kali linux is not a supported distribution

### ISSUE THREAD

**Issue by deadpoint** [saltstack-formulas/openssh-formula#115]
This formula is not support on Kali Linux because the os_family grain is 'Kali' and not 'Debian'. Adding a mapping in map.jinja, which I've included below, will resolve the issue. I will fork and submit a pull request, but figured given how simple the fix is it would be quick for one of the maintainers to make it.

```
--- a/openssh/map.jinja
+++ b/openssh/map.jinja
@@ -17,6 +17,11 @@ that differ from whats in defaults.yaml
       'client': 'openssh-client',
       'service': 'ssh',
     },
+    'Kali': {
+      'server': 'openssh-server',
+      'client': 'openssh-client',
+      'service': 'ssh',
+    },
     'FreeBSD': {
       'service': 'sshd',
       'dig_pkg': 'bind-tools',
```

Error when attempting to apply the state.
```
[salt.state       ][CRITICAL][52394] Rendering SLS 'base:openssh' failed: Jinja error: 'NoneType' object is not iterable
/var/cache/salt/minion/files/base/openssh/map.jinja(53):
---
[...]
  , grain="os_family"
  , merge=salt['pillar.get']('openssh:lookup'))
%}

{## Merge the flavor_map to the default settings ##}
{% do default_settings.openssh.update(os_family_map) %}    <======================

{## Merge in openssh:lookup pillar ##}
{% set openssh = salt['pillar.get'](
    'openssh',
    default=default_settings.openssh,
[...]
---
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1073, in make_module
    return TemplateModule(self, self.new_context(vars, shared, locals))
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1152, in __init__
    body_stream = list(template.root_render_func(context))
  File "/var/cache/salt/minion/files/base/openssh/map.jinja", line 53, in top-level template code
    {% do default_settings.openssh.update(os_family_map) %}
TypeError: 'NoneType' object is not iterable
```

**Comment by rhertzog** [comment]
This should probably be fixed in salt itself: https://github.com/saltstack/salt/blob/develop/salt/grains/core.py#L1241

Kali should have os_family = Debian.

**Comment by rhertzog** [comment]
In fact the Kali->Debian mapping is already there. It was committed here: https://github.com/saltstack/salt/commit/0e3c4475673badb00059897cc6ee1042a865e126

So I'm closing the ticket.
