### ISSUE TITLE
Ubuntu Bug

### ISSUE THREAD

**Issue by charles-d-burton** [saltstack-formulas/openssh-formula#42]
I'm running into a bug when using this with Ubuntu 14.04.  I enabled it in my top.sls, but it fails to run on Ubuntu and spits out this error:

```
    Data failed to compile:
----------
    Rendering SLS "base:openssh" failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 77, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 169, in render_jinja_tmpl
    output = jinja_env.from_string(tmplstr).render(**unicode_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1013, in make_module
    return TemplateModule(self, self.new_context(vars, shared, locals))
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1070, in __init__
    self._body_stream = list(template.root_render_func(context))
  File "/var/cache/salt/minion/files/base/openssh/map.jinja", line 50, in top-level template code
    {% set openssh = salt['pillar.get'](
TypeError: get() got an unexpected keyword argument 'merge'

----------
```

**Comment by ingben** [comment]
I think I had a similar issue after installing an outdated salt version from the Ubuntu repositories.

When you have followed the official [howto](https://docs.saltstack.com/en/latest/topics/installation/ubuntu.html), you will likely end up with something like the following:
```
root@vagrant-ubuntu-trusty-64:~# apt-cache show salt-master
Package: salt-master
Source: salt
Priority: extra
Section: admin
Installed-Size: 145
Maintainer: Joe Healy <joehealy@gmail.com>
Architecture: all
Version: 2015.5.2+ds-1trusty1
Recommends: python-git
Depends: sysv-rc (>= 2.88dsf-24) | file-rc (>= 0.8.16), python, python:any (>= 2.6~), salt-common (= 2015.5.2+ds-1trusty1), python-m2crypto, python-crypto, python-msgpack, python-zmq (>= 13.1.0)
Filename: pool/main/s/salt/salt-master_2015.5.2+ds-1trusty1_all.deb
Size: 39412
MD5sum: 380f773b4ebc2bdd0e6d7bf355b5aca0
SHA1: 677ddb3cd3f7b755ca34e6da5d05127039456c03
SHA256: 06591be1c1ed54236425af28257b590e5169dead7f90207d4ef7ff0fdb3f3a74
Description-en: remote manager to administer servers via salt
 salt is a powerful remote execution manager that can be used to
 administer servers in a fast and efficient way.
 .
 It allows commands to be executed across large groups of
 servers. This means systems can be easily managed, but data can
 also be easily gathered.  Quick introspection into running
 systems becomes a reality.
 .
 Remote execution is usually used to set up a certain state on a
 remote system. Salt addresses this problem as well, the salt
 state system uses salt state files to define the state a server
 needs to be in.
 .
 Between the remote execution system, and state management Salt
 addresses the backbone of cloud and data center management.
 .
 This particular package provides the salt controller.
Description-md5: 36e948d6f2dba9c67d0fe58bcec6ff6a

Package: salt-master
Priority: optional
Section: universe/admin
Installed-Size: 132
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Salt Team <pkg-salt-team@lists.alioth.debian.org>
Architecture: all
Source: salt
Version: 0.17.5+ds-1
Depends: init-system-helpers (>= 1.13~), sysv-rc (>= 2.88dsf-24) | file-rc (>= 0.8.16), python:any, salt-common (= 0.17.5+ds-1), python-m2crypto, python-crypto, python-msgpack, python-zmq (>= 13.1.0)
Filename: pool/universe/s/salt/salt-master_0.17.5+ds-1_all.deb
Size: 28100
MD5sum: d94b4a24396408b71e0d985bcaf2a8e8
SHA1: 9bb7f0a13f18b1f3b5fcf2c7ee68746f6385a009
SHA256: 5da0be71b4c7f0a752c8a863609b89c7333ca7cbce58556acdc2abdafc52a19f
Description-en: remote manager to administer servers via salt
 salt is a powerful remote execution manager that can be used to
 administer servers in a fast and efficient way.
 .
 It allows commands to be executed across large groups of
 servers. This means systems can be easily managed, but data can
 also be easily gathered.  Quick introspection into running
 systems becomes a reality.
 .
 Remote execution is usually used to set up a certain state on a
 remote system. Salt addresses this problem as well, the salt
 state system uses salt state files to define the state a server
 needs to be in.
 .
 Between the remote execution system, and state management Salt
 addresses the backbone of cloud and data center management.
 .
 This particular package provides the salt controller.
Description-md5: 36e948d6f2dba9c67d0fe58bcec6ff6a
Homepage: http://saltstack.org/
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
```

On my box, ``sudo apt-get install salt-master`` will install version ``0.17.5+ds-1``.

If that is the case for you as well, try to install a more recent version, e.g. like so:
```
sudo apt-get install salt-master=2015.5.2+ds-1trusty1
```

The same applies to the ``salt-minion``.

**Comment by RichardLaing** [comment]
Adding the repo and updating fixed the issue for me. 

Thank you.

**Comment by ketzacoatl** [comment]
Sounds like this issue could be closed?

**Comment by gravyboat** [comment]
Yeah I'm going to close this for now especially since Salt is now hosting their own repo.
